version: '3.8'

services:
  rtmp-server:
    build: .
    ports:
      - "${RTMP_PORT:-1935}:${RTMP_PORT:-1935}"  # RTMP port (configurable)
      - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"   # HTTP port (configurable)
    volumes:
      - .:/app  # Mount project directory for live sync
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - OBS_PASSWORD=${OBS_PASSWORD:-your_password}
      - OBS_WEBSOCKET_PORT=${OBS_WEBSOCKET_PORT:-4455}
      - RTMP_PORT=${RTMP_PORT:-1935}
      - HTTP_PORT=${HTTP_PORT:-8000}
      - DOCKER_HOST_IP=host.docker.internal
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    container_name: rtmp-server
    command: npm run dev  # Use nodemon for auto-restart on changes